---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
      version: blue
  template:
    metadata:
      name: mynginx
      labels:
        app: web
        version: blue
    spec:
      containers:
      - name: mynginx
        image: zubairbhat722/nginximage::latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: mynginx
  labels:
    app: web
spec:
  selector:
    app: web
    version: blue
  type: NodePort
  ports:
  - nodePort: 31113
    port: 80
    targetPort: 80
